# Generated by Django 4.1.2 on 2022-11-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haircuts', '0002_haircut_time_execution'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('haircut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='haircuts.haircut')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.master')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
