# Generated by Django 4.1.3 on 2022-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_start_time_appointment_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
