# Generated by Django 4.1.4 on 2022-12-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_entry_date_alter_appointment_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='entry_time',
            field=models.TextField(),
        ),
    ]
