//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PovarenokApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counters
    {
        public int CounterID { get; set; }
        public int TableCounter { get; set; }

        public int GetNext()
        {
            CounterID++;
            return CounterID - 1;
        }
    }
}
