//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PovarenokApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public string OrderProducts { get; set; }
        public string OrderQuantities { get; set; }
        public System.DateTime OrderOrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderStatus { get; set; }
    }
}
