//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;

namespace PovarenokApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int ProductCategory { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public byte[] ProductImage { get; set; }

        public bool IsEmpty()
        {
            return string.IsNullOrEmpty(ProductName);
        }

        public string DiscountText
        {
            get
            {
                if (ProductDiscountAmount == 0)
                    return string.Empty;
                else
                    return $"* скидка {ProductDiscountAmount}%";
            }
        }

        public string Title => string.Join(" ", ProductName, ":", ProductQuantityInStock.ToString());
        public string Cost => ProductCost.ToString("0.00") + " ";

        public string TotalCost
        {
            get
            {
                if (ProductDiscountAmount == 0)
                    return ProductCost.ToString("0.00") + " рублей";
                else
                    return ((float)ProductCost * (1 - ProductDiscountAmount / 100f)).Value.ToString("0.00") + " рублей";
            }
        }

        public Visibility DiscountVisibility
        {
            get
            {
                if (ProductDiscountAmount == 0)
                    return Visibility.Collapsed;
                else
                    return Visibility.Visible;
            }
        }

        public string BackColor
        {
            get
            {
                if (ProductDiscountAmount == 0)
                    return "#FFFFE1";
                else
                    return "#D1FFD1";
            }
        }

        public Products DeepCopy()
        {
            return new Products()
            {
                ProductID = ProductID,
                ProductCategory = ProductCategory,
                ProductCost = ProductCost,
                ProductDiscountAmount = ProductDiscountAmount,
                ProductQuantityInStock = ProductQuantityInStock,
                ProductName = ProductName,
                ProductImage = ProductImage
            };
        }
    }
}
