//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PovarenokApp.Data
{
    using System;
    using System.Collections.Generic;
    using PovarenokApp.Data.Enum;


    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPatronymic { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int UserRole { get; set; }

        public bool IsAdmin()
        {
            return (Role)UserRole == Role.Admin;
        }

        public static UserEntity Empty = new UserEntity()
        {
            id = 0,
            first_name = string.Empty,
            last_name = string.Empty,
            patronymic = string.Empty,
            login = string.Empty,
            password = string.Empty,
            role = (int)Role.NotUser
        };

        public static UserEntity SuperUser = new UserEntity()
        {
            id = 0,
            first_name = string.Empty,
            last_name = string.Empty,
            patronymic = string.Empty,
            login = string.Empty,
            password = string.Empty,
            role = (int)Role.Admin
        };
    }
}
