# Generated by Django 4.1.5 on 2023-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('article', models.PositiveIntegerField(default=10000)),
                ('price', models.PositiveIntegerField(default=1000)),
                ('image', models.ImageField(null=True, upload_to='Products', verbose_name='Изображение')),
                ('type', models.CharField(choices=[('CF', 'Coffin'), ('WR', 'Wreath'), ('CR', 'Crosses'), ('MN', 'Monument'), ('TX', 'Textile'), ('N', 'None')], default='N', max_length=2)),
            ],
        ),
    ]
