# Generated by Django 4.1.5 on 2023-01-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('CF', 'Гробы'), ('WR', 'Венки'), ('CR', 'Кресты на могилу'), ('MN', 'Памятники на могилу'), ('TX', 'Текстиль'), ('N', 'Пусто')], default='N', max_length=2, verbose_name='Тип товара'),
        ),
    ]
