# Generated by Django 4.1.4 on 2022-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=500, null=True, verbose_name='Продукты')),
                ('quantity', models.CharField(max_length=500, null=True, verbose_name='Количества')),
                ('total_quantity', models.PositiveIntegerField(null=True)),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
    ]
