# Generated by Django 4.1.4 on 2022-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sizes',
            field=models.CharField(max_length=500, null=True, verbose_name='Размеры'),
        ),
    ]
