# Generated by Django 4.1.2 on 2022-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.URLField(default=None)),
                ('image2', models.URLField(default=None)),
                ('image3', models.URLField(default=None)),
                ('image4', models.URLField(default=None)),
                ('image5', models.URLField(default=None)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(default=None)),
            ],
        ),
    ]
