# Generated by Django 4.1.2 on 2022-10-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haircut',
            old_name='body',
            new_name='description',
        ),
    ]
