# Generated by Django 4.1.2 on 2022-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='time_execution',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
