# Generated by Django 4.1.2 on 2022-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='full_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='haircut',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
