# Generated by Django 4.1.4 on 2022-12-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Shirts', verbose_name='Изображение')),
                ('title', models.CharField(default='none', max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('size_width', models.PositiveIntegerField()),
                ('size_heigth', models.PositiveIntegerField()),
                ('thickness', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
