# Generated by Django 4.1.4 on 2022-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='size_heigth',
        ),
        migrations.RemoveField(
            model_name='package',
            name='size_width',
        ),
        migrations.AddField(
            model_name='package',
            name='size',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
