# Generated by Django 4.1.4 on 2022-12-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haircuts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('article', models.TextField(default=None)),
                ('haircut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='haircuts.haircut')),
            ],
        ),
    ]
