# Generated by Django 4.1.2 on 2022-11-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haircuts', '0002_haircut_time_execution'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='haircut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='haircuts.haircut'),
        ),
    ]
