# Generated by Django 4.1.4 on 2022-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity_units',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
