# Generated by Django 4.1.4 on 2022-12-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_quantity_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='Адрес'),
        ),
    ]
