# Generated by Django 4.1.4 on 2022-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_products',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
